# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :debian do |debian|
    debian.vm.box = "chef/debian-7.8"
  end

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.box = "chef/ubuntu-14.04"
  end

  config.vm.provision "shell", path: "../install.sh"
end
